added mechanism to kill process group

diff --git a/ext-conf/init.d/collectd b/ext-conf/init.d/collectd
--- a/ext-conf/init.d/collectd
+++ b/ext-conf/init.d/collectd
@@ -15,7 +15,7 @@
 # Set APP_STARTS_WITH_JAVA=1 if the is started using java directly  
 #
 # Set APP_SELF_CONTAINED if the has its on var/run, var/log, var/lock structure
-# like ecos
+# like ecos, instead of using the system /var/log for example
 #
 # Set APP_RESOLVE_LINK=1 if you don't need the script to follow link to script to resolve
 # location
@@ -26,12 +26,22 @@
 # 
 # Set APP_DOES_NOT_MANAGE_PID_FILE=1 if this app does not create its own pidfile
 # 
+# Set APP_ROTATES_OWN_LOG_FILE=1 if this app has its own way of rotating logs 
+# 
+# Set APP_STOP_NEED_TO_KILL_GROUP=1 if you want use a hammer to make sure the daemon
+# and all its children go away. It does not allow the daemon to manage this on his own.
+# ----- Use with care.
+# 
 #
 # NB: Make sure you set APP_MAIN to something that is recongizable and distict
 # form the process command line. This string is used to verify that the pid matches 
 # the process. For Java apps, this variable should be set to the name of the main class
 # even if this script doesn't start the app directly. 
 # For regular processes the app name usually suffice, $APP_DEAMON should work fine
+#
+# If you are having trouble with the startup, it is often because we don't find the
+# string expected in /proc/<pid>/cmdline. Uncomment the line in check() that cats out
+# the cmdline so you can verify that we are grepping for the right pattern
 #
 # Look for "Set to fit app" for section that you may want to edit for new app
 
@@ -46,7 +56,15 @@ APP_RESOLVE_LINK=0
 APP_WARDEN_CONTROLLED=1
 APP_DEAMONIZES=1
 APP_DOES_NOT_MANAGE_PID_FILE=0
+APP_ROTATES_OWN_LOG_FILE=0
+APP_STOP_NEED_TO_KILL_GROUP=1
 
+
+if [ $APP_STOP_NEED_TO_KILL_GROUP -eq 1 ]; then
+    KILL_GROUP="-- -"
+else
+    KILL_GROUP=""
+fi
 
 SCRIPT_DIR=$(dirname $0)
 SCRIPT_NAME=${0##*/}
@@ -63,6 +81,8 @@ ACTUAL_SCRIPT_NAME="${ACTUAL_LOCATION##*/}"
 APP_HOSTNAME=$(hostname --fqdn)
 
 #if MAPR_HOME isn't set figure it out
+# You need to alter the /*/*/etc/init.d and /etc/init.d patterns here if your structure
+# is different
 MAPR_HOME="${MAPR_HOME:-${ACTUAL_LOCATION%/*/*/etc/init.d/${ACTUAL_SCRIPT_NAME}}}"
 APP_HOME_DIR="${ACTUAL_LOCATION%/etc/init.d/${ACTUAL_SCRIPT_NAME}}"
 APP_DATA_DIR_PERM=0700
@@ -82,7 +102,8 @@ fi
 
 # Need to run this early so that things like JAVA_HOME is setup early
 if [ -f "$APP_ENV_SCRIPT" ]; then
-    # exit if we don't find a complete and compatible JDK
+    # exit if we don't find a complete and compatible JDK - 
+    # this is only for our env.sh, and may need altering for something different
     JDK_REQUIRED=1
     . "$APP_ENV_SCRIPT"
     if [ -n "$JAVA_HOME" -a -x "$JAVA_HOME/bin/java" ]; then
@@ -99,7 +120,8 @@ if [ $APP_SELF_CONTAINED -eq 1 ]; then
     APP_LOCK_DIR=${APP_HOME_DIR}/var/lock/subsys
     APP_LOCK_FILE="$APP_LOCK_DIR/$APP"
     APP_LOG_DIR="$APP_HOME_DIR/var/log/$APP"
-    APP_LOG_FILE="$APP_LOG_DIR/$APP.log"
+    APP_LOG_FILE="$APP_LOG_DIR/$APP.log"                   # use this for aps own logging 
+    APP_LOG_START_FILE="$APP_LOG_DIR/${APP}_startup.log"   # use this for startup logging
     APP_CONF_DIR="$APP_HOME_DIR/etc"
     APP_CONF_FILE="$APP_CONF_DIR/$APP.conf"
     APP_DATA_DIR="$APP_HOME_DIR/var/lib/$APP"
@@ -109,7 +131,8 @@ else
     APP_LOCK_DIR=${APP_HOME_DIR}/var/lock/subsys
     APP_LOCK_FILE="$APP_LOCK_DIR/$APP"
     APP_LOG_DIR="$APP_HOME_DIR/logs"
-    APP_LOG_FILE="$APP_LOG_DIR/$APP.log"
+    APP_LOG_FILE="$APP_LOG_DIR/$APP.log"                   # use this for aps own logging 
+    APP_LOG_START_FILE="$APP_LOG_DIR/${APP}_startup.log"   # use this for startup logging
     APP_DATA_DIR="$APP_HOME_DIR/data"
     APP_PID_DIR="$APP_HOME_DIR/data"
     APP_PID_FILE="$APP_PID_DIR/$APP.pid"
@@ -139,7 +162,7 @@ else
 fi
 
 # FILL IN java main class - like com.mapr.installer.InstallerApplication if it is a
-# java app, otherwise set it to APP_DEAMON
+# java app, otherwise set it to APP_DEAMON(usually)
 
 APP_MAIN="$APP_DAEMON"
 
@@ -180,16 +203,26 @@ check_and_setup_system() {
 check() {
     local sig=$1
     [ -z "$sig" ] && sig=0
-    if [ ! -r "$APP_DATA_DIR" ]; then
+    if [ ! -r "$APP_PID_DIR" ]; then
         echo "$APP permission denied"
     elif [ $APP_DEAMONIZES -eq 1 ] ; then
         APP_PID=$(cat $APP_PID_FILE 2> /dev/null)
     fi
     if [ -n "$APP_PID" ]; then
-        if kill -$sig $APP_PID > /dev/null 2>&1; then
+        if [ "$sig" = "0" ]; then
+            KILL_ARGS="-$sig $APP_PID"
+        else
+            KILL_ARGS="-$sig $KILL_GROUP$APP_PID"
+        fi
+        if kill $KILL_ARGS > /dev/null 2>&1; then
             # check if it is truly $APP
             local file=/proc/$APP_PID/cmdline
             [ ! -f $file ] && return
+            # If you are having trouble with startup, uncomment this line to see what
+            # the command line looks like. When underlying services are execed, 
+            # the string we need to grep for migh be very different than what we expect
+            #
+            # cat $file
             grep -q $APP_MAIN $file && return
         fi
         rm -f $APP_PID_FILE
@@ -246,9 +279,14 @@ start() {
     mkdir -m $APP_DATA_DIR_PERM -p "$APP_DATA_DIR"
     mkdir -p "$APP_LOG_DIR" "$APP_PID_DIR"
 
-    # Manage log 
-    rotate_log "$APP_LOG_FILE"
-    touch "$APP_LOG_FILE"
+    # Manage logs
+    rotate_log "$APP_LOG_START_FILE"
+    touch "$APP_LOG_START_FILE"
+
+    if [ $APP_ROTATES_OWN_LOG_FILE -eq 0 ]; then
+        rotate_log "$APP_LOG_FILE"
+        touch "$APP_LOG_FILE"
+    fi
 
     # make sure ulimits/kernel options are set
     check_and_setup_system
@@ -279,9 +317,9 @@ start() {
     if [ $APP_STARTS_WITH_JAVA -eq 1 ]; then
         "$JAVA" -Dlog.file="$APP_LOG_FILE" -Djava.library.path="$APP_JAVA_LIBRARY_PATH" \
             -classpath "$APP_CLASSPATH" $APP_OPTS_1 $APP_OPTS_2 $MAPR_SSL_OPTS \
-           "$APP_MAIN" $* >> "$APP_LOG_FILE" 2>&1 < /dev/null &
+           "$APP_MAIN" $* >> "$APP_LOG_START_FILE" 2>&1 < /dev/null &
     else
-        $APP_DAEMON $APP_OPTS_1 $APP_OPTS_2 $* >> "$APP_LOG_FILE" 2>&1 < /dev/null &
+        $APP_DAEMON $APP_OPTS_1 $APP_OPTS_2 $* >> "$APP_LOG_START_FILE" 2>&1 < /dev/null &
     fi
     APP_PID=$!
     # do not overwrite service managed pid file and wait for process to write it
@@ -292,7 +330,7 @@ start() {
     until [ $i -eq 100 ]; do
         sleep 0.3
         if check && [ -s "$APP_PID_FILE" ]; then
-            echo "$APP ($APP_PID) started with log $APP_LOG_FILE"
+            echo "$APP ($APP_PID) started with log $APP_LOG_START_FILE"
             if [ $APP_SELF_CONTAINED -o "$uid" = "root" ]; then
                 [ -d "$LOCK_DIR" ] && touch "$APP_LOCK_FILE"
             fi
@@ -302,7 +340,7 @@ start() {
     done
     check TERM && sleep 2 && check KILL
     wait $APP_PID
-    echo "$APP ($APP_PID) start failed ($?). See $APP_LOG_FILE for details"
+    echo "$APP ($APP_PID) start failed ($?). See $APP_LOG_START_FILE for details"
     false
 }
 
@@ -338,11 +376,6 @@ stop() {
     fi
     false
 }
-
-if [ -n "$APP_ULIMIT_MAX_LOCKED_MEMORY" -a -z "$ES_HEAP_SIZE" ]; then
-    echo "APP_ULIMIT_MAX_LOCKED_MEMORY is set - ES_HEAP_SIZE must also be set"
-    exit 2
-fi
 
 if [ $APP_DOES_NOT_MANAGE_PID_FILE -eq 1 -a $APP_DEAMONIZES -eq 1 ] ;then
     echo "We have no way of managing the pid file"
